const data = {
  products: [
    {
      name: 'Dragon',
      slug: 'dragon',
      category: 'Fantasy',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Lizard',
      slug: 'lizard',
      category: 'animals',
      image: '/images/p2.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Octopus',
      slug: 'octopus',
      category: 'animals',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      name: 'Crocodile',
      slug: 'crocodile',
      category: 'animals',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
  ],
};

export default data;
